### PR TITLE
Build package for conda-forge from source and AARCH migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/cramjam-feedstock/pull/14/

I'm just trying this to see if it is easy. I probably won't try much harder than this.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martindurant** [comment]
In the build log, it seems like the package built (compiled and made into conda package), but after installation it doesn't import.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
> In the build log, it seems like the package built (compiled and made into conda package), but after installation it doesn't import.

It seems that maturin is finding python 3.9 but not in the installation prefix. Is there a way to specify which python is being used by maturin?

**Comment by hmaarrfk** [comment]
Typically, you don't need many htings in build, but so lets see what happens.

It was being built for python 3.9, even though the host had python 3.8 installed.

**Comment by milesgranger** [comment]
Can use `maturin build -i python` to specify which python

**Comment by martindurant** [comment]
If maturin would be in the build instead of/aswell as in host section?

**Comment by hmaarrfk** [comment]
Can the `-i` flag provide a full path?

```
    -i, --interpreter <interpreter>...
            The python versions to build wheels for, given as the names of the interpreters. Uses autodiscovery if not
            explicitly set
```

**Comment by hmaarrfk** [comment]
> If maturin would be in the build instead of/aswell as in host section?

Typically only one or the other.

When you are cross compiling, take for example OSX, I think you need something to be in the `build` section.  The `build` targets a specific `host`, and then runs in the `run` environment.

**Comment by hmaarrfk** [comment]
@martindurant depending on the exact nature of the build tools, some exist only in `build`: 
- cmake
- make
- compilers

are good examples.

**Comment by hmaarrfk** [comment]
TBH, i'm not sure if OSX is cross compiling correctly. I think if we add enough things to the build section, it will work eventually, but i'm not entirely sure it is correct.

**Comment by martindurant** [comment]
Add as many things in `build` as you can think of! None of those contribute to the final size of the static library.

**Comment by hmaarrfk** [comment]
I have a feeling this will be successful. But I might be wrong.

**Comment by hmaarrfk** [comment]
This is definitely the right way to do it for aarch and ppc64le, i'm just unsure about osx cross compilation.

**Comment by hmaarrfk** [comment]
If you are OK with this, then I would merge this and then issue a botrerun (via a label) to the aarch migration.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Review by milesgranger — APPROVED** [review]
Whoa! This would have taken me forever to figure out, nice work! I at least give my approval for it, but probably not qualified to do so. :sweat_smile:

**Comment by hmaarrfk** [comment]
you can just put the label "botautomerge" to get it to merge later.

**Comment by hmaarrfk** [comment]
@martindurant  found the other missing dependencies (I just squashed a few commits, sorry).

**Comment by martindurant** [comment]
It's fine with me

**Comment by hmaarrfk** [comment]
Sorry the usual native builds <-> azure dance is happening. While azure is slower, it is more reliable in terms of finishing builds.

**Comment by hmaarrfk** [comment]
My guess is that the aarch builds are going to Fail.
@martindurant you can try Azure, but for some reason compilation failed. Not sure how it detected it was running in QEMU.

I would suggest restarting the AARCH builds that are running natively on drone and fail in master.

**Comment by hmaarrfk** [comment]
i.e. merge as is, and babysit for a bit.

**Comment by martindurant** [comment]
I'm OK with all this, I'll leave it to @milesgranger to press the button, if the above makes sense to you.

**Comment by hmaarrfk** [comment]
For clarity. drone has two "size" arm cores.

If you get "lucky" and you hit a "big core" your builds go quickly.

If you get "unlucky" and you hit a "small core" your builds essentially never finish due to the 1 hour limit.


Sometimes you can bulid on Azure via qemu (6 hour limit, but roughly 6 times as slow as the "big core"), but for some reason, it isn't working here.

**Comment by milesgranger** [comment]
Can you clarify what you mean by babysitting it? Does it just fail occasionally and need a restart every now and again?

**Comment by hmaarrfk** [comment]
Yes. Specifically restarting select jobs on drone (where the restart button is easy to press unlike azure).

**Comment by milesgranger** [comment]
Thanks again for your help with this, I really appreciate it!! :raised_hands:

**Comment by hmaarrfk** [comment]
no problem.

**Comment by hmaarrfk** [comment]
It seems that only one job on drone failed!

**Comment by milesgranger** [comment]
and maybe I'm being oblivious, but I don't see how to restart the failed run... :face_with_head_bandage: 
image

**Comment by milesgranger** [comment]
Not that it matters much now, but we got ppc64le to compile as [`manylinux2014_ppc64le`](https://pypi.org/project/cramjam/#copy-hash-modal-d087e8a1-2183-4a60-84ed-a6ff97b26272) where before the ppc64le build failed b/c `manylinux_2_24_ppc64le` was only recognized by a pip version greater than the one that's currently on conda.

**Comment by hmaarrfk** [comment]
Can you try to login on the bottom left?

**Comment by milesgranger** [comment]
Do all four need to pass before it uploads or so long as the failed one passes during some retry it's good? Restarted twice so far and at least one has failed each time, but the 3.6 has passed on the second now.

**Comment by milesgranger** [comment]
I'm assuming so long as all four pass at some point it's good...
`Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.`

**Comment by hmaarrfk** [comment]
Yeah. At some point.

Thanks for checking. 

Making an empty commit is a good way to do it.

**Pull request merged**
