### PR TITLE
Update to 2.5.0, add python3.10, and fix cross-compiling

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by milesgranger** [comment]
Thanks @erykoff !! :pray: 

For me, I'm good with almost anything which gets this up on conda in the easiest and _maintainable_ way possible.

Strong preference for anything which uses [existing wheels, without any dependencies, already on PyPi](https://pypi.org/project/cramjam/#files). These include Python 3.10 for basically every distribution and think it was one of the first to have PyPy 3.8 support. :wink: 

That said, I'm ironically not the best person to review this PR.

**Comment by martindurant** [comment]
Unfortunately, there are very few of us that are qualified to have an opinion with this stuff! It looks like the build is not succeeding on linux_aarch and ppc.

**Comment by erykoff** [comment]
So the bad news is that I have no idea how to get the aarch64 and ppc64le jobs working; in the meantime I'm going to revert back to native...
The worse news is that my changes to `meta.yaml` didn't appear to fix the osx-arm64 cross builds.  At least my local test didn't work, which was a bit convoluted because I'm using an emulated x86 env on my M1 mac and then trying to do a cross-build to arm64.
I think that using existing wheels as-is is considered a "last resort" on conda-forge, but I also have no idea how to get maturin to do cross compiling...

**Comment by erykoff** [comment]
And I'm also wondering where the osx-arm64 py310 wheels are on pypi.

**Comment by erykoff** [comment]
Apparently the pinned version of libmimalloc-sys 0.1.23 doesn't support aarch64 or ppc64le; if this was updated upstream in the Cargo files then I think that would make those builds work.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by erykoff** [comment]
Okay, the rust compiler misconfigure that @isuruf noticed is the reason that the arm64 cross compile wasn't working.  Locally I was able to successfully cross compile.  So this PR should fix #17 at least.

**Comment by erykoff** [comment]
Oh dear lord, the cross-builds with python 3.10 think that the python version is 3.1 and then failing.  Any idea where this check is happening and failing?

**Comment by martindurant** [comment]
From conda people: "3.10 needs to be a string in the yaml file"

**Comment by erykoff** [comment]
it's actually a bug in `conda-build`.  Working on it...

**Comment by erykoff** [comment]
Okay, this really is good to go.

To summarize: the version has been updated to 2.5.0, which properly supports cross compilation and python3.10; the python3.10 builds have been added to the matrix; and the proper `PYO3_CROSS` env vars have been set and the correct rust compiler is selected so that cross compilation works correctly, fixing #17 .

**Review by milesgranger — APPROVED** [review]
Awesome, thanks so much for the time and effort here! Got my approval at least. 

> And I'm also wondering where the osx-arm64 py310 wheels are on pypi.

Thanks for this as well, noticed it was an error in yaml string comparison; has been fixed and it's on PyPI now. :+1:

**Comment by erykoff** [comment]
I am definitely going to be looking out for erroneous string comparisons in github actions from here on out ...

Anyway, feel free to merge whenever.  This will then allow fastparquet to be migrated to py310 (as well as fixing the osx-arm64 conda forge installation!).

**Comment by martindurant** [comment]
>  This will then allow fastparquet to be migrated to py310 

Only with my self-made thrift :). https://github.com/dask/fastparquet/pull/633

**Comment by erykoff** [comment]
Ha!  Well, this is necessary if not sufficient ...

**Pull request merged**
